### ISSUE TITLE
Map out search functionallity

### ISSUE THREAD

**Issue by brandong954** [jrpeden/cs373-idb#128]
The result of a search must be a list of links to crises and/or organizations and/or people (e.g. like Google).
The search results must be contextualized and the search terms must show up.
The search results must be clickable.
Multi-word search must show clearly marked and results followed by or results.

**Comment by brandong954** [comment]
@lazercorn, I'll need your help with this on the backend. Here's some helpful material I've come up with so far: https://github.com/gyllstromk/Flask-WhooshAlchemy

**Comment by tiras-j** [comment]
Aww I wanted to dive into this one as well. Mind if I help out Saturday?

**Comment by brandong954** [comment]
As per convo on Slack:

hah yeah, I’ll actually need your help with the API
Perry will need to setup the database to be indexable
You’ll setup the API call for searches
And I’ll set up the factories and states
Jack and Zach can pair-program on stuff too

**Comment by tiras-j** [comment]
Ah nice. I really wish I could get slack working on my work PC, alas this network is heavily firewalled. Excited about this little feature should be a fun puzzle.
