### ISSUE TITLE
Create a page that exercises the API of another group in an interesting and useful way.

### ISSUE THREAD

**Issue by brandong954** [jrpeden/cs373-idb#130]
The page must have a clear English description and be rendered attractively. Group exercise order will be:

```
Group 1 exercises Group 2.
Group 2 exercises Group 3.
...
Group N exercises Group 1.
```

**Comment by tiras-j** [comment]
I'd like to take a stab at this one, just to get some front-end playtime. But I'll probably need a bit of assistance from Brandon or Jack at some point as well :)

**Comment by brandong954** [comment]
For sure!

**Comment by jrpeden** [comment]
So we're assigned to use the College Football group's API. Perry came up with a clever idea of making a page where we compare the "average NBA player" with the "average college football player" using stat averages (height, weight, age, etc...). Seems doable enough, depending on what stats the other team serves up.

**Comment by jrpeden** [comment]
Just so we can get it done, I've started work on this feature. I made a basic template that will compare the weight of a random NBA player with a random NCAA football player, called "Who Weighs More?". So far I've got the template and most of the controller, and now I'm working on the factory.

**Comment by jrpeden** [comment]
Shippable
