### ISSUE TITLE
Improve the technical report.

### ISSUE THREAD

**Issue by brandong954** [jrpeden/cs373-idb#134]
For this phase make it at least 5,000 words.
Document the search capabilities well.

**Comment by brandong954** [comment]
Search capabilities will be under the Design section

**Comment by brandong954** [comment]
As per Aseal:

For the report use cases are suppose to be cases in which a user would use your website. You just talked about your website's functionality. It also looks like you lifted your description of Apiary directly from their website. You need to cite it or paraphrase it. Player names are probably not a good primary key.

**Comment by brandong954** [comment]
Add the planitpoker stuff: http://www.planitpoker.com/board/#/room/e4140f5ce638491c8088163f07fdd46a
estimate them, include assumptions
discuss them
refine the estimates
implement them
track how long each took
document them in your GitHub Wiki

**Comment by okruhlik** [comment]
done.
