### ISSUE TITLE
Use http://www.planitpoker.com or https://www.planningpoker.com to: 

### ISSUE THREAD

**Issue by brandong954** [jrpeden/cs373-idb#135]
```
set up at least 10 user stories
user stories must be described in three sentences or less
estimate them, include assumptions
discuss them
refine the estimates
implement them
track how long each took
document them in your GitHub Wiki
```

**Comment by brandong954** [comment]
setting this up now

**Comment by brandong954** [comment]
Join our planitpoker room: http://www.planitpoker.com/board/#/room/e4140f5ce638491c8088163f07fdd46a

brandong954 [3:51 PM]
Everyone create at least two stories

brandong954 [3:51 PM]
user stories must be described in three sentences or less

brandong954 [3:52 PM]
We’ll then estimate them, include assumptions, discuss them, and refine the estimates after 10 stories have been created

**Comment by tiras-j** [comment]
"User needs to be able to accurately and accessibly extract data via documented API"
"User should have access to modular static API endpoints as well as dynamic endpoints utilizing query parameters"
I can't seem to add to the planit poker site

**Comment by brandong954** [comment]
done
