### ISSUE TITLE
Add full functionality to Apiary test console

### ISSUE THREAD

**Issue by tiras-j** [jrpeden/cs373-idb#147]
Now that we have all the APIs operational we can add the functionality to allow test API calls to be issued via Apiary console. Essentially I set up the Apiary documentation with test data sets (calls or responses) and you can run them against the actual API hosted by the site (assuming it's up). I don't think this is a requirement but I figure why not.

**Comment by brandong954** [comment]
Noice!

**Comment by tiras-j** [comment]
Yep yep it's there, you can hit the API from the test console on Apiary now. Lets you fill out arguments and see what gets returned.
