### ISSUE TITLE
API calls for search need to return everything for games, players, and teams

### ISSUE THREAD

**Issue by brandong954** [jrpeden/cs373-idb#154]
Just like we did for the views, we need to return everything for a given keyword.

For example, if I do a search for Dwyane, I just get the player data, but I need games and the team to be appended onto the returned data object.

**Comment by brandong954** [comment]
Supposedly works for "Tim", but when I try "Dwyane", I only get the player

**Comment by tiras-j** [comment]
This was implemented, however I believe we have shifted away from this requirement. Closing for now.
