### ISSUE TITLE
Implement tables for data

### ISSUE THREAD

**Issue by brandong954** [jrpeden/cs373-idb#36]
This looks like it will work nicely with our setup: http://angular-ui.github.io/ng-grid/

**Comment by jrpeden** [comment]
Tables current work on their own in a test vacuum. Need to integrate into Bootstrap and the site structure as a whole. Individual pages will need names to match how the table links are looking for them.

**Comment by brandong954** [comment]
Going to pair program with Jack on this one

**Comment by jrpeden** [comment]
Tables are ready to go and point to the correct pages.
