### ISSUE TITLE
Setup the needed pages for Crisis, Organizations, and People

### ISSUE THREAD

**Issue by brandong954** [jrpeden/cs373-idb#37]
Create a set of static HTML pages for three crises, three organizations, and three people that displays all of the data collected (issue #36 will handle the data part).
The pages must be served by Rackspace using Django or Flask to embed the static content into the HTML.

**Comment by jrpeden** [comment]
These pages will need to be named in a specific way so that the table links can find them. I can elaborate once we put the tables on the site.

**Comment by brandong954** [comment]
Done
