### ISSUE TITLE
Resolve SHA-1 Certficiate Error

### ISSUE THREAD

**Issue by brandong954** [jrpeden/cs373-idb#84]
Keep getting this message in the console:

This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More]

**Comment by jrpeden** [comment]
Looks like this is caused by getting those two pieces of Angular from ajax.googleapis.com/ajax/libs in index.html. Google still uses SHA-1 for that API access, so the only resolution I've found online is to switch over to storing Angular locally.

**Comment by brandong954** [comment]
Done
